service: serverless-express-api
plugins:
  - serverless-offline
  - serverless-plugin-typescript
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 512
functions:
  handler:
    handler: index.generate
    events:
      - websocket: 
          route: $connect
      - websocket: 
          route: $disconnect 
      - http: 
          path: /crawl
          method: POST
          cors: true
          
